#### This notebook shows a placeholder example of how labeled data can be created; it is illustrative rather than a fully functional implementation.

In [ ]:
import dask.dataframe as dd
import pandas as pd

In [ ]:
data = dd.read_csv(r'data')

In [3]:
data.head()

,Composite Element REF,TCGA-AQ-A0Y5-01A,TCGA-EW-A2FW-01A,TCGA-C8-A274-01A,TCGA-AC-A62V-01A,TCGA-B6-A0IK-01A,TCGA-E2-A1L7-01A,TCGA-E9-A247-01A,TCGA-AR-A0U0-01A,TCGA-E2-A1LI-01A,...,TCGA-A1-A0SI-01A,TCGA-A2-A0SX-01A,TCGA-BH-A0B3-11B,TCGA-BH-A0B3-01A,TCGA-BH-A0HF-01A,TCGA-LD-A7W5-01A,TCGA-S3-A6ZG-01A,TCGA-AR-A250-01A,TCGA-E9-A22E-01A,TCGA-S3-AA11-01A
0,cg00000029,0.123206,0.070247,0.095459,0.149745,0.213110,0.239587,0.063008,0.270560,0.292818,...,0.222990,0.403554,0.186394,0.344942,0.148349,0.355298,NaN,0.096609,NaN,0.129366
1,cg00000108,0.955195,0.898010,0.973301,0.962013,0.965753,0.967329,0.976577,0.955460,0.970097,...,0.963308,0.958564,0.967886,0.962070,0.967611,0.969314,0.961262,0.959671,0.912241,0.969402
2,cg00000109,0.924968,0.936458,0.926613,0.929127,0.925687,0.953052,0.908876,0.925157,0.911863,...,0.930014,0.931631,0.832615,0.892051,0.885744,0.901302,0.918371,0.910686,0.870502,0.812195
3,cg00000165,0.673627,NaN,0.891222,NaN,0.766033,0.331990,0.859703,NaN,0.550584,...,0.252024,0.679362,0.219337,0.679683,0.201634,0.352060,NaN,0.813755,NaN,0.797948
4,cg00000236,0.901612,0.803841,0.942629,0.930383,0.902132,0.924075,0.933446,0.917999,0.906572,...,0.928599,0.900594,0.918503,0.919749,0.934357,0.941520,0.924583,0.889700,0.883032,0.864668

In [4]:
pandas_df = data.compute()

In [5]:
BIA = pd.read_csv('D:\Kuliah\Semester 6\Dataset\TCGA-BRCA.clinical.csv')

<>:1: SyntaxWarning: invalid escape sequence '\K'
<>:1: SyntaxWarning: invalid escape sequence '\K'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_28320\539613132.py:1: SyntaxWarning: invalid escape sequence '\K'
  BIA = pd.read_csv('D:\Kuliah\Semester 6\Dataset\TCGA-BRCA.clinical.csv')

In [6]:
pandas_df = pandas_df.dropna()

In [7]:
yang_kepake2 = BIA[["sample", "ajcc_pathologic_stage.diagnoses"]]
yang_kepake2

                sample ajcc_pathologic_stage.diagnoses
0     TCGA-BH-A0W3-01A                       Stage IIA
1     TCGA-AR-A24V-01A                       Stage IIB
2     TCGA-E9-A1NE-01A                       Stage IIB
3     TCGA-E9-A1NE-11A                       Stage IIB
4     TCGA-AC-A8OQ-01A                       Stage IIB
...                ...                             ...
1250  TCGA-BH-A1FH-11B                        Stage IV
1251  TCGA-BH-A1FH-01A                        Stage IV
1252  TCGA-AR-A1AO-01A                       Stage IIA
1253  TCGA-A7-A0D9-01A                       Stage IIA
1254  TCGA-A7-A0D9-11A                       Stage IIA

[1255 rows x 2 columns]

In [8]:
dask_df = pandas_df.set_index('Composite Element REF')

In [9]:
Transposed =  dask_df.T
Transposed

Composite Element REF,cg00000108,cg00000109,cg00000236,cg00000292,cg00000321,cg00000363,cg00000622,cg00000658,cg00000714,cg00000721,...,cg27665648,cg27665659,cg27665715,cg27665767,cg27665769,cg27665808,cg27665860,cg27665925,cg27665985,cg27666046
TCGA-AQ-A0Y5-01A,0.955195,0.924968,0.901612,0.759490,0.545766,0.479092,0.012156,0.849487,0.089075,0.950177,...,0.831809,0.062260,0.981234,0.525596,0.399193,0.420886,0.795797,0.034003,0.066783,0.314732
TCGA-EW-A2FW-01A,0.898010,0.936458,0.803841,0.875491,0.600452,0.176351,0.013624,0.885482,0.110990,0.962936,...,0.835043,0.060602,0.984505,0.707457,0.493080,0.109512,0.752239,0.018921,0.071061,0.417523
TCGA-C8-A274-01A,0.973301,0.926613,0.942629,0.450042,0.768147,0.835801,0.016575,0.852908,0.089694,0.950627,...,0.838815,0.052236,0.978180,0.836097,0.476961,0.676255,0.909549,0.019982,0.181432,0.429994
TCGA-AC-A62V-01A,0.962013,0.929127,0.930383,0.821076,0.608490,0.598694,0.013518,0.919552,0.105946,0.962027,...,0.580397,0.053720,0.980507,0.248180,0.299881,0.250372,0.743603,0.021168,0.187149,0.851444
TCGA-B6-A0IK-01A,0.965753,0.925687,0.902132,0.615725,0.574990,0.542504,0.008904,0.915041,0.088762,0.950102,...,0.866880,0.039126,0.978901,0.599609,0.315045,0.408384,0.765025,0.293406,0.164641,0.357934
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-LD-A7W5-01A,0.969314,0.901302,0.941520,0.825792,0.518104,0.551027,0.014539,0.884182,0.186821,0.957988,...,0.738590,0.122338,0.979482,0.509210,0.371478,0.491789,0.630080,0.074169,0.343186,0.526889
TCGA-S3-A6ZG-01A,0.961262,0.918371,0.924583,0.765740,0.662753,0.354157,0.014890,0.868653,0.187116,0.928191,...,0.669494,0.081804,0.987141,0.690239,0.109221,0.588885,0.838848,0.016324,0.221824,0.257730
TCGA-AR-A250-01A,0.959671,0.910686,0.889700,0.582140,0.640055,0.686199,0.015411,0.836841,0.128227,0.951901,...,0.797260,0.063320,0.981901,0.728612,0.428042,0.667064,0.703607,0.025203,0.123666,0.162941
TCGA-E9-A22E-01A,0.912241,0.870502,0.883032,0.598557,0.378294,0.250627,0.011838,0.881013,0.122367,0.934663,...,0.757406,0.167253,0.969462,0.769345,0.393810,0.084826,0.764194,0.025288,0.224190,0.465617
TCGA-S3-AA11-01A,0.969402,0.812195,0.864668,0.925828,0.611688,0.796927,0.014656,0.892971,0.149813,0.940171,...,0.801540,0.070558,0.980607,0.463537,0.412654,0.198908,0.797431,0.019769,0.307507,0.203859

In [ ]:
mapping = yang_kepake2.set_index('sample')['ajcc_pathologic_stage.diagnoses'].str.replace('Stage ', '')

UMN_Horizontal = Transposed.assign(Label=Transposed.index.map(mapping))

In [16]:
Labeled = UMN_Horizontal

In [17]:
Labeled['Label'].value_counts()

Label
IIA     96
IIB     80
IIIA    45
I       30
IA      16
IIIC    14
IIIB     8
IV       2
IB       2
X        2
II       1
Name: count, dtype: int64

In [18]:
Labeled.head()

Composite Element REF,cg00000108,cg00000109,cg00000236,cg00000292,cg00000321,cg00000363,cg00000622,cg00000658,cg00000714,cg00000721,...,cg27665659,cg27665715,cg27665767,cg27665769,cg27665808,cg27665860,cg27665925,cg27665985,cg27666046,Label
TCGA-AQ-A0Y5-01A,0.955195,0.924968,0.901612,0.759490,0.545766,0.479092,0.012156,0.849487,0.089075,0.950177,...,0.062260,0.981234,0.525596,0.399193,0.420886,0.795797,0.034003,0.066783,0.314732,IIIA
TCGA-EW-A2FW-01A,0.898010,0.936458,0.803841,0.875491,0.600452,0.176351,0.013624,0.885482,0.110990,0.962936,...,0.060602,0.984505,0.707457,0.493080,0.109512,0.752239,0.018921,0.071061,0.417523,IIA
TCGA-C8-A274-01A,0.973301,0.926613,0.942629,0.450042,0.768147,0.835801,0.016575,0.852908,0.089694,0.950627,...,0.052236,0.978180,0.836097,0.476961,0.676255,0.909549,0.019982,0.181432,0.429994,IIA
TCGA-AC-A62V-01A,0.962013,0.929127,0.930383,0.821076,0.608490,0.598694,0.013518,0.919552,0.105946,0.962027,...,0.053720,0.980507,0.248180,0.299881,0.250372,0.743603,0.021168,0.187149,0.851444,IV
TCGA-B6-A0IK-01A,0.965753,0.925687,0.902132,0.615725,0.574990,0.542504,0.008904,0.915041,0.088762,0.950102,...,0.039126,0.978901,0.599609,0.315045,0.408384,0.765025,0.293406,0.164641,0.357934,IIIB

In [19]:
Labeled['Label'] = Labeled['Label'].apply(lambda x: 'Early' if x in ['I', 'IB', 'IV', 'IA', 'IIA', 'IIB', 'II', 'X'] else 'Late')

In [20]:
Labeled['Label'].value_counts()

Label
Early    229
Late      70
Name: count, dtype: int64

In [21]:
Labeled.head()

Composite Element REF,cg00000108,cg00000109,cg00000236,cg00000292,cg00000321,cg00000363,cg00000622,cg00000658,cg00000714,cg00000721,...,cg27665659,cg27665715,cg27665767,cg27665769,cg27665808,cg27665860,cg27665925,cg27665985,cg27666046,Label
TCGA-AQ-A0Y5-01A,0.955195,0.924968,0.901612,0.759490,0.545766,0.479092,0.012156,0.849487,0.089075,0.950177,...,0.062260,0.981234,0.525596,0.399193,0.420886,0.795797,0.034003,0.066783,0.314732,Late
TCGA-EW-A2FW-01A,0.898010,0.936458,0.803841,0.875491,0.600452,0.176351,0.013624,0.885482,0.110990,0.962936,...,0.060602,0.984505,0.707457,0.493080,0.109512,0.752239,0.018921,0.071061,0.417523,Early
TCGA-C8-A274-01A,0.973301,0.926613,0.942629,0.450042,0.768147,0.835801,0.016575,0.852908,0.089694,0.950627,...,0.052236,0.978180,0.836097,0.476961,0.676255,0.909549,0.019982,0.181432,0.429994,Early
TCGA-AC-A62V-01A,0.962013,0.929127,0.930383,0.821076,0.608490,0.598694,0.013518,0.919552,0.105946,0.962027,...,0.053720,0.980507,0.248180,0.299881,0.250372,0.743603,0.021168,0.187149,0.851444,Early
TCGA-B6-A0IK-01A,0.965753,0.925687,0.902132,0.615725,0.574990,0.542504,0.008904,0.915041,0.088762,0.950102,...,0.039126,0.978901,0.599609,0.315045,0.408384,0.765025,0.293406,0.164641,0.357934,Late

In [ ]:
Labeled.to_csv('Labelled.csv', index=False)