In [1]:
import pandas as pd

In [ ]:
manifest = pd.read_csv(
    r'TestFinal\ForCGP\GeneMapping\humanmethylation450_15017482_v1-2.csv', #Since the data is quite heavy this data can be downloaded via https://support.illumina.com/downloads/humanmethylation450_15017482_v1-2_product_files.html
    skiprows=7  
)

manifest

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_3248\3876115595.py:1: DtypeWarning: Columns (2,4,11,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  manifest = pd.read_csv(

,IlmnID,Name,AddressA_ID,AlleleA_ProbeSeq,AddressB_ID,AlleleB_ProbeSeq,Infinium_Design_Type,Next_Base,Color_Channel,Forward_Sequence,...,UCSC_RefGene_Group,UCSC_CpG_Islands_Name,Relation_to_UCSC_CpG_Island,Phantom,DMR,Enhancer,HMM_Island,Regulatory_Feature_Name,Regulatory_Feature_Group,DHS
0,cg00035864,cg00035864,31729416,AAAACACTAACAATCTTATCCACATAAACCCTTAAATTTATCTCAA...,NaN,NaN,II,NaN,NaN,AATCCAAAGATGATGGAGGAGTGCCCGCTCATGATGTGAAGTACCT...,...,TSS1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,cg00050873,cg00050873,32735311,ACAAAAAAACAACACACAACTATAATAATTTTTAAAATAAATAAAC...,31717405.0,ACGAAAAAACAACGCACAACTATAATAATTTTTAAAATAAATAAAC...,I,A,Red,TATCTCTGTCTGGCGAGGAGGCAACGCACAACTGTGGTGGTTTTTG...,...,Body;TSS1500,chrY:9363680-9363943,N_Shore,NaN,NaN,NaN,Y:9973136-9976273,NaN,NaN,NaN
2,cg00061679,cg00061679,28780415,AAAACATTAAAAAACTAATTCACTACTATTTAATTACTTTATTTTC...,NaN,NaN,II,NaN,NaN,TCAACAAATGAGAGACATTGAAGAACTAATTCACTACTATTTGGTT...,...,Body;Body;Body,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,cg00063477,cg00063477,16712347,TATTCTTCCACACAAAATACTAAACRTATATTTACAAAAATACTTC...,NaN,NaN,II,NaN,NaN,CTCCTGTACTTGTTCATTAAATAATGATTCCTTGGATATACCAAGT...,...,Body,chrY:22737825-22738052,S_Shelf,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,cg00121626,cg00121626,19779393,AAAACTAATAAAAATAACTTACAAACCAAATACTATACCCTACAAC...,NaN,NaN,II,NaN,NaN,AGGTGAATGAAGAGACTAATGGGAGTGGCTTGCAAGCCAGGTACTG...,...,Body,chrY:21664481-21665063,N_Shore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486423,65622344,NORM_T,Purple,Norm_T59,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486424,57640346,NORM_C,Green,Norm_C60,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486425,47715450,NORM_T,Purple,Norm_T60,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486426,28673402,NORM_C,Green,Norm_C61,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486427,13742412,NORM_T,Purple,Norm_T61,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
used_data = manifest[['IlmnID', 'UCSC_RefGene_Name']]
used_data

            IlmnID UCSC_RefGene_Name
0       cg00035864            TTTY18
1       cg00050873    TSPY4;FAM197Y2
2       cg00061679    DAZ1;DAZ4;DAZ4
3       cg00063477            EIF1AY
4       cg00121626            BCORL2
...            ...               ...
486423    65622344               NaN
486424    57640346               NaN
486425    47715450               NaN
486426    28673402               NaN
486427    13742412               NaN

[486428 rows x 2 columns]

In [39]:
ForMatching =  pd.read_csv(r'D:\Kuliah\Semester 6\Notebook\Listed_CPG.csv')
ForMatching

     Unnamed: 0         CPG
0             0  cg05380003
1             1  cg00021030
2             2  cg22183731
3             3  cg03954667
4             4  cg20370783
..          ...         ...
207         207  cg09155852
208         208  cg18531164
209         209  cg24112733
210         210  cg01054282
211         211  cg17584085

[212 rows x 2 columns]

In [40]:
used = ForMatching['CPG']
used

0      cg05380003
1      cg00021030
2      cg22183731
3      cg03954667
4      cg20370783
          ...
207    cg09155852
208    cg18531164
209    cg24112733
210    cg01054282
211    cg17584085
Name: CPG, Length: 212, dtype: object

In [55]:
merged = pd.merge(daga, used_data, left_on='sample', right_on='IlmnID', how='inner')


result = merged[['sample', 'UCSC_RefGene_Name']]

print(result)

        sample                                UCSC_RefGene_Name
0   cg00107488                                      COMT;TXNRD2
1   cg00132108                                              NaN
2   cg00463767                                             OTX1
3   cg00497967                                            VAT1L
4   cg00697290                                              NaN
..         ...                                              ...
95  cg26667395                                          PPP1R3C
96  cg26681822                                             TLR6
97  cg26893861                                            DUSP3
98  cg26939283                                             KPRP
99  cg27079776  PCDHGA2;PCDHGA4;PCDHGA1;PCDHGA4;PCDHGB1;PCDHGA3

[100 rows x 2 columns]

In [57]:
result.to_csv('GeneCpnverted.csv')

In [53]:
daga = daga
daga

,sample,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,cg00107488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,cg00132108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,cg00463767,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,cg00497967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,cg00697290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,cg26667395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,cg26681822,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,cg26893861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,cg26939283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,cg27079776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
daga = pd.read_csv('D:\Kuliah\Semester 6\TestFinal\DataBaru.csv')

<>:1: SyntaxWarning: invalid escape sequence '\K'
<>:1: SyntaxWarning: invalid escape sequence '\K'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_3248\3202664317.py:1: SyntaxWarning: invalid escape sequence '\K'
  daga = pd.read_csv('D:\Kuliah\Semester 6\TestFinal\DataBaru.csv')